site_name: Workshop dbt + PostgreSQL + Metabase
site_url: ""
nav:
    - Home: index.md
    - Part 1 -  Setup your environment:  part1setup.md
    - Part 2 - Install dbt: part2dbt.md
    - Part 3 - Ingest data (badly): part3ingest.md
    - Part 4 - Transform data with dbt: part4transform.md
    - Part 5 - Build documentation: part5documentation.md
    - Part 6 - Visualize with Metabase: part5metabase.md
    - Conclusion: part6conclusion.md
theme: material
repo_url: https://github.com/baaastijn/dbt-postgresql-metabase-workshop
repo_name: baaastijn/dbt-postgresql-metabase-workshop

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences